version: '3'
services:
  py:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - .:/usr/src/app
      - ./site-packages:/usr/local/lib/python3.6/site-packages
